# Generated by go2rpm 1.8.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/ProtonMail/go-crypto
%global goipath         github.com/ProtonMail/go-crypto
%global commit          4b6e5c58789592be5b16c8b1a00d2b765a2e7dc8

%gometa

%global common_description %{expand:
Fork of go/x/crypto, providing an up-to-date OpenPGP implementation.}

%global golicenses      LICENSE PATENTS
%global godocs          AUTHORS README.md CONTRIBUTORS

Name:           %{goname}
Version:        0
Release:        0.5%{?dist}
Summary:        Fork of go/x/crypto, providing an up-to-date OpenPGP implementation

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
* Thu Jul 21 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.4
- Rebuilt for https://fedoraproject.org/wiki/Fedora_37_Mass_Rebuild

* Thu Jan 20 2022 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_36_Mass_Rebuild

* Thu Jul 22 2021 Fedora Release Engineering <releng@fedoraproject.org> - 0-0.2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_35_Mass_Rebuild

* Wed Dec 09 10:58:56 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0-0.1.20201209git11f6ee2
- Initial package
